# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.cache/wt [current_project]
set_property parent.project_path /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/Trans.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/mux8.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/mod8.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/Tetris_biblio.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/random_gen_v1.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/anti_rebond.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/Anti_reponds.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/Afficheur_7SEG.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/vga_bitmap_160x100.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/Gestion_temps.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/Controller.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/Board_Controller.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/Affichage.vhd
  /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/sources_1/new/Total.vhd
}
read_xdc /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/constrs_1/new/Tetris_DDR.xdc
set_property used_in_implementation false [get_files /net/e/amouhagir/Desktop/project_Tetris/project_Tetris.srcs/constrs_1/new/Tetris_DDR.xdc]

synth_design -top Total -part xc7a100tcsg324-3
write_checkpoint -noxdef Total.dcp
catch { report_utilization -file Total_utilization_synth.rpt -pb Total_utilization_synth.pb }
